---
title: "index"
author: "E Irving"
date: "13/04/2022"
output: html_document
runtime: shiny
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(here)
library(tidyverse)
library(shiny)
library(ggrepel)
```

# My Practice project

This is my practice file for the Data Visualisation Module

```{r dataimport}
#importing of the data

pwbestlocalauth <- read.csv(here("data", "pwbest_localauth_filtered.csv"))
#head(df)
```


```{r datawrangling}
##data wrangling is needed to rename and remove columns that are not necessary for visualisation
#rename: change column/variable names to something short
pwbestlocalauth <- pwbestlocalauth %>% 
  rename(Geography = Title, pwb = X, '2016-17' = X.2, '2017-18' = X.6, '2018-19' = X.10, '2019-20' = X.14, '2020-21' = X.18)

# use select to just look at some columns
pwbestlocalauth <- pwbestlocalauth %>% 
  select(Geography, pwb, '2016-17', '2017-18','2018-19', '2019-20', '2020-21')
head(pwbestlocalauth)

#remove rows from dataset
pwbestlocalauth <- pwbestlocalauth[-c(1,2),]
#head(pwbestlocalauth)
```

```{r scatterplot}
p <- ggplot(pwbestlocalauth,aes(x=pwb,y=`2016-17`,color = Geography))
p + geom_smooth(alpha=0.3, method = 'lm') + labs(x = "Personal Wellbeing Measures",
                                                                 y = "Scores", title = "Personal Wellbeing Scores in 2016-2017") + geom_jitter(height=0,width=.1,alpha=.5) + geom_text_repel(aes(label=Geography))

ggsave(here("figs", "16-17plot.png"))
```

```{r Shiny}

ui <- shinyUI(fluidPage(
  titlePanel("Personal Wellbeing Scores across the UK"),
  sidebarLayout(
    sidebarPanel(
      radioButtons(inputId = "year", #created a button panel for the user to select the year they wish to view
                   label = "Please select a year:",
                   choices=c("2016-17" = "2016-17", "2017-18" = "2017-18","2018-19" = "2018-19", "2019-20" = "2019-20","2020-21" = "2020-21"),
                   selected = "2016-17" #automatically set on the year 2016-2017
      )),
    
    mainPanel(
      plotOutput("scatterplot") #output should be a scatter plot
    )
  )
))

#now to instruct the server what to display 
server <- shinyServer(function(input,output){
  output$scatterplot <- renderPlot({#ggplot used to create a scatterplot of the data depending on year picked by user
   ggplot(pwbestlocalauth, aes(x= pwb, y=get(input$year), color = Geography)) + geom_point() + geom_smooth(alpha=0.3, method = 'lm') + labs(x = "Personal Wellbeing Measures", y = "Scores", title = "Personal Wellbeing Scores") + geom_text_repel(aes(label=Geography))
  })
})

shinyApp(ui, server)
```


# Discussion

This practice project has enabled me to produce simple ggplots with my data, as well as creating a shiny interface where different graphs can be shown based on the year a user is interested in.


